# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

blb_mix <- function(y, b, s, r, d) {
    .Call('_bumblb_blb_mix', PACKAGE = 'bumblb', y, b, s, r, d)
}

