# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Mixture Model Bag of Little Bootstraps with Optional Annealing and Non-Uniform
#' Sampling
#'
#' This function returns a list containing the estimated probabilities, means,
#' standard deviations and log likelihoods of the fitted GMM. Implemented in
#' C++
#'
#' @param y Numeric data vector
#' @param b Bag of Little Bootstraps sample size
#' @param s Number of sample (of size b) to be taken
#' @param r Number of Monte Carlo iterations for each sample
#' @param d Number of distributions in mixture model
#' @param pr_ Optional vector of sampling probabilities. If null, sampling is
#' uniform
#' @param pi_ Optional vector of prior distribution probabilities
#' @param mu_ Optional vector of distribution means
#' @param sd_ Optional vector of distribution standard deviations
#' @param max_iter Maximum number of iterations for EM algorithm. Default is
#' 10,000
#' @param tol Tolerance for convergence of log likelihood for EM algorithm.
#' @param beta Optional parameter representing the starting \eqn{\beta} for
#' annealing. For the default of 1, standard EM algorithm is run. Only needs to
#' be specified for annealing if schedule_ is left NULL
#' @param c Optional secondary parameter that determines growth rate of
#' \eqn{\beta}. Only needs to be specified for annealing if schedule_ is left
#' NULL
#' @param schedule_ Optional scheduling for annealing, if not set to NULL the
#' schedule given will be used in place of the beta and c parameters.
#'
#' @return List containing probability, standard deviation, and log likelihood
#' values
#'
#'
#' @export
blb_mix <- function(y, b, s, r, d, pr_ = NULL, pi_ = NULL, mu_ = NULL, sd_ = NULL, max_iter = 10000L, tol = 1e-5, beta = 1.0, c = 1.1, schedule_ = NULL) {
    .Call('_bumblb_blb_mix', PACKAGE = 'bumblb', y, b, s, r, d, pr_, pi_, mu_, sd_, max_iter, tol, beta, c, schedule_)
}

#' GMM with Optional Annealing
#'
#' This function returns a list containing the estimated probabilities, means,
#' standard deviations and log likelihoods of the fitted GMM. Implemented in
#' C++
#'
#' @param Y Numeric data vector
#' @param d Number of distributions in mixture model
#' @param pi_ Optional vector of prior distribution probabilities
#' @param mu_ Optional vector of distribution means
#' @param sd_ Optional vector of distribution standard deviations
#' @param max_iter Maximum number of iterations for EM algorithm. Default is
#' 10,000
#' @param tol Tolerance for convergence of log likelihood for EM algorithm.
#' @param beta Optional parameter representing the starting \eqn{\beta} for
#' annealing. For the default of 1, standard EM algorithm is run. Only needs to
#' be specified for annealing if schedule_ is left NULL
#' @param c Optional secondary parameter that determines growth rate of
#' \eqn{\beta}. Only needs to be specified for annealing if schedule_ is left
#' NULL
#' @param schedule_ Optional scheduling for annealing, if not set to NULL the
#' schedule given will be used in place of the beta and c parameters.
#'
#' @return List containing probability, standard deviation, and log likelihood
#' values
#'
#'
#' @export
gmm <- function(Y, d, pi_ = NULL, mu_ = NULL, sd_ = NULL, max_iter = 10000L, tol = 1e-5, beta = 1.0, c = 1.1, schedule_ = NULL) {
    .Call('_bumblb_gmm', PACKAGE = 'bumblb', Y, d, pi_, mu_, sd_, max_iter, tol, beta, c, schedule_)
}

